### ISSUE TITLE
Search bots generating modscript errors on addon.php

### ISSUE THREAD

**Issue by oricgn** [Phorum/Core#1000]
It is part of the nature of search bots to visit each know webpage (also) without any query string even if all original links have a query string.

addon.php triggers each time an error if "module" is missing.

I think it shouldn't be treated as an error if the script is called without a query string. Only an incomplete query string should trigger an error message.

Perhaps it's a good idea to redirect search bots to index.php.

**Comment by cactux** [comment]
> Perhaps it's a good idea to redirect search bots to index.php.
This should be done very carefully, as it can have a bad impact on SEO. If a page as a different behavior for a bot than for a regular user, then it is flagged as suspicious by the bot.
If you meant "addon.php should redirect to index.php *when there's no module*", then ok, but for all users, not only bots (even if only bots should send such request).

**Comment by oricgn** [comment]
Yes, you are right, I mean "addon.php should redirect to index.php when there's no query string".

**Comment by oricgn** [comment]
Same to css.php.

**Comment by oricgn** [comment]
Fixed in master and branch_5_2
