### ISSUE TITLE
phorum-5.2.22.tar.gz seems not a valid gzip-compressed tarball

### ISSUE THREAD

**Issue by jschleus** [Phorum/Core#1018]
I just downloaded http://www.phorum.org/downloads/phorum-5.2.22.tar.gz (md5sum 933b60790d2cfa2ece193844c8221952) but cannot extract that file. The program "file" just says "data".
But the file http://www.phorum.org/downloads/phorum-5.2.22.zip was extractable.

**Comment by oricgn** [comment]
I uploaded the tar.gz once more and tested the download. No problem to extract now.

Thanks!
