### ISSUE TITLE
Make registration and password restore language file entries consistent

### ISSUE THREAD

**Issue by Phorum** [Phorum/Core#607]
The other email messages that are defined in the language file, make use of replacement %strings% and use only one language file entry. The registration and password restore language strings are split in two halves for the body. A single body with a %placeholder% for the data that goes in the middle would be more in line with the other mail messages and it would make it posible for modules like the Customize Mail Messages module to easily modify the mail message.

Reported by: mmakaay
Imported from TRAC: http://trac.phorum.org/ticket/707

**Comment by oricgn** [comment]
Already done in branch "master".

**Comment by oricgn** [comment]
Do you want a backport to branch 5.2?
