### ISSUE TITLE
Smiley module: bug with entities and smiley substitution

### ISSUE THREAD

**Issue by Phorum** [Phorum/Core#827]
There a subtle bug in the smileys module. Sample string a user writes into a message
{{{
")
}}}
The smiley module utilizes the `format_fixup` hook which receives this data:
{{{
&quot;)
}}}
Now the smiley module, which by default contains the `;)` smiley, replaces this into
{{{
&quot<img ....
}}}

I first tried to attack this with a single `preg_replace()` for subject/body by using PCREs negative lookbehind assertions, unfortunately they do not support variable pattern lengths. This is the best pattern I came up with, which isn't supported:
{{{
/(?<!&([A-Za-z]+|#[0-9]+));\)/

preg_replace(): Compilation failed: lookbehind assertion is not fixed length
}}}

Second approach was to first use `preg_split` to split the string on the entities and then build it back again and only apply smiley replacement on the non-entity captured elements (they're the only ones with a `&` at the start). This is the solution we're using now, patch is attached.

Reported by: Markus  <markus@fischer.name>
Imported from TRAC: http://trac.phorum.org/ticket/933

**Comment by oricgn** [comment]
Patch included in Phorum 5.2 with commit https://github.com/Phorum/Core/commit/99081711fcb254d10f86b361d4faa1b69585383e and in 5.3 with commit https://github.com/Phorum/Core/commit/409e98b1f1dd60c68895ac30608913986e9d8d2b
