### ISSUE TITLE
stale file purge ignores tempfiles

### ISSUE THREAD

**Issue by Phorum** [Phorum/Core#860]
There is bug in stale file purge procedure. Currently it purges only files of type '''PHORUM_LINK_EDITOR'''.
I have significant amount of stale files of type '''PHORUM_LINK_TEMPFILE'''. They should be detected and purged as well in ''phorum_db_list_stale_files()''

just change SQL to:

WHERE (link = '".PHORUM_LINK_EDITOR."' OR link = '".PHORUM_LINK_TEMPFILE."' )
AND
add_datetime < .......
      

Reported by: hsn
Imported from TRAC: http://trac.phorum.org/ticket/968

**Comment by oricgn** [comment]
Fixed for Phorum 5.2 with commit https://github.com/Phorum/Core/commit/d3af3ad116c9bf05db523dff1090e9bfd94e9023 and for Master with commit https://github.com/Phorum/Core/commit/decdf879afb421268d12efc1212e4f84b7dfb383.
