### ISSUE TITLE
Feeds are producing invalid XML

### ISSUE THREAD

**Issue by philip** [Phorum/Core#887]
The feed will sometimes insert invalid (multibyte) characters thus rendering the XML (for RSS/Atom) invalid. Phorum should ensure that the feeds produce valid XML.

I stole a user comment from the PHP manual that helped the feed to validate (by removing non-standard ascii characters) but it likely won't work for general purposes as it simply deletes "invalid" characters. But the code is:

  $new = preg_replace("/[^\x9\xA\xD\x20-\x7F]/", "", $old);

Unfortunately I'm not sure what this mysterious character is but I do have the generated XML here and may attach it to this bug report.

**Comment by oricgn** [comment]
No confirmation in he last three years... Closing this issue.
