### ISSUE TITLE
No Activation or Password reminder emails

### ISSUE THREAD

**Issue by wayno-complaino** [Phorum/Core#900]
I'm trying to register on forum.reprap.org but don't receive any activation email.  I have trued with two different email addresses and checked all spam filters/junk mailboxes.  If I ask for password reminders there is still no email.  I'd really like to be able to post on this forum please.

Any help appreciated.

Thanks

**Comment by mysnip** [comment]
Hi, we are not running that site, they are just using our software.
You should contact the site owner.
