### ISSUE TITLE
[2.1.19] String offset cast occurred in /var/www/phorum/mods/spamhurdles/api.php on line 771

### ISSUE THREAD

**Issue by dcaillibaud** [Phorum/Core#902]
With phorum 2.1.19 and php 5.4.40, after a lot of spam attempts (without success), I had 6Go of php notice with

```
PHP Notice:  String offset cast occurred in /var/www/phorum/mods/spamhurdles/api.php on line 771
```

I have also a lot of
```
PHP Notice:  unserialize(): Error at offset 2222 of 2718 bytes in /var/www/phorum/include/db/mysql.php on line 585

PHP Notice:  unserialize(): Error at offset 1769 of 1957 bytes in /var/www/phorum/include/db/mysql.php on line 768

PHP Notice: unserialize(): Error at offset 7744 of 7957 bytes in /var/www/phorum/include/db/mysql.php on line 1350

PHP Notice: unserialize(): Error at offset 110 of 135 bytes in /var/www/phorum/include/db/mysql.php on line 1441

PHP Notice:  unserialize(): Error at offset 1322 of 3794 bytes in /var/www/phorum/include/db/mysql.php on line 1470

PHP Notice:  unserialize(): Error at offset 493 of 585 bytes in /var/www/phorum/include/db/mysql.php on line 3348
```
perhaps data related, and

```
PHP Notice: Undefined index: HTTP_USER_AGENT in /var/www/phorum/mods/mod_mobile/mod_mobile.php on line 14

PHP Warning:  strpos(): Empty needle in /var/www/phorum/mods/bbcode/api.php on line 1313

PHP Notice:  Undefined index: body in /var/www/phorum/mods/post_previews/post_previews.php on line 75
```

It's not so important, It's always possible not to log notice, but I prefer keep this because notice are often a sign of possible bug.

Thanks for phorum, and if possible for removing theses notice in a next release

**Comment by oricgn** [comment]
> PHP Notice:  String offset cast occurred in 
> /var/www/phorum/mods/spamhurdles/api.php on line 771

For the 5.2 branch done in https://github.com/Phorum/Core/commit/c975a095efb9d205925539e6523adbe0eed19805, master branch not involved.

**Comment by oricgn** [comment]
> PHP Notice:  Undefined index: body in /var/www/phorum/mods/post_previews/post_previews.php
> on line 75

Fixed in version 5.2.1.06 of the Post Previews Module:
http://www.phorum.org/phorum5/read.php?62,133957,156051#msg-156051

**Comment by oricgn** [comment]
> PHP Notice: Undefined index: HTTP_USER_AGENT in
> /var/www/phorum/mods/mod_mobile/mod_mobile.php on line 14

Fixed in Version 1.0.3 of the Automatic Mobile Template Module:
http://www.phorum.org/phorum5/read.php?62,147914,156052#msg-156052

**Comment by oricgn** [comment]
> PHP Warning:  strpos(): Empty needle in /var/www/phorum/mods/bbcode/api.php
> on line 1313

For the 5.2 branch done in https://github.com/Phorum/Core/commit/a53da5473faa6998716eda6e156a7e5e57ba02ad and for master in https://github.com/Phorum/Core/commit/cc6a1d9b2b120d697de90767c9ad40d1f3820a95.

**Comment by oricgn** [comment]
> PHP Notice:  unserialize(): Error at offset 2222 of 2718 bytes in /var/www/phorum/include/db/mysql.php

Except last warning it concerns always to the meta column. I think this could be the same issue: http://davidwalsh.name/php-serialize-unserialize-issues

> It turns out that if there's a ", ', :, or ; in any of the array values the serialization gets corrupted.

**Comment by oricgn** [comment]
Or your database does not have proper collation for your Phorum database tables:
http://www.jackreichert.com/2014/02/02/handling-a-php-unserialize-offset-error/
