### ISSUE TITLE
user verification

### ISSUE THREAD

**Issue by charlieb000** [Phorum/Core#904]
I get a link to verify my membership to a Phorum forum like so:
http://forums.reprap.org/register.php?80,approve=51d1b44444555

after clicking on it, it gets changed to this by the web-email interface (hotmail)
http://forums.reprap.org/register.php?80%2capprove=51d1b44444555

this does not work. i get the "create a new profile" page instead of verification.
Wasn't immediately obvious!

Charlie.

**Comment by mysnip** [comment]
Well, thats simply a web mail client mangling with a link where it shouldn't. Nothing we can do about it.
