### ISSUE TITLE
Module Tidy Output is corrupting avatar images

### ISSUE THREAD

**Issue by oricgn** [Phorum/Core#911]
See: http://www.phorum.org/phorum5/read.php?61,153673

It seems that function phorum_ob_clean in common.php cause the problem.

Since php 5.4 ob_get_status doesn't return an array when buffer is empty. In my testcase ob_get_status() returns 1. Because of this phorum_ob_clean doesn't call ob_end_clean().

**Comment by oricgn** [comment]
Sorry I'm wrong, ob_get_status returns an array but the array keys changed:

#############################
PHP 5.4 an above

If called without the full_status parameter or with full_status = FALSE a simple array with the following elements is returned:

Array
(
    [name] => myhandler
    [type] => 1
    [flags] => 20593
    [level] => 0
    [chunk_size] => 0
    [buffer_size] => 16384
    [buffer_used] => 0
)

* name: the first element returned by get_list_handlers()
* type: PHP_OUTPUT_HANDLER_INTERNAL = 0,  PHP_OUTPUT_HANDLER_USER = 1. Note ob_start() without a parameter and output_buffering=on are each type 0.
* flags: type plus additional flags. In the example above, it is the sum of:
** PHP_OUTPUT_HANDLER_USER = 0x0001 = 1
** PHP_OUTPUT_HANDLER_CLEANABLE = 0x0010 = 16
** PHP_OUTPUT_HANDLER_FLUSHABLE = 0x0020 = 32
** PHP_OUTPUT_HANDLER_REMOVABLE = 0x0040 = 64
** PHP_OUTPUT_HANDLER_STARTED = 0x1000 = 4096
** PHP_OUTPUT_HANDLER_PROCESSED = 0x4000 = 16384
* level: 0-based nesting level, one less than get_ob_level()
* chunk_size: parameter in ob_start()
* buffer_size
* buffer_used

In PHP 5.3 and below, it is:

Array
(
    [level] => 1
    [type] => 1
    [status] => 1
    [name] => myhandler
    [del] => 1
)

* level: 1-based nesting level, the same as get_ob_level()
* type: 0 internal, 1 user. The meaning differs from later PHP. For example, ob_start() without a parameter is type 1.
* status: 0 before buffering, 1 while buffering, possibly other values
* name: the first element returned by get_list_handlers()
* del: erase parameter in ob_start()

##############################

**Comment by mysnip** [comment]
Thanks a lot!
