### ISSUE TITLE
retire lists.phorum.org

### ISSUE THREAD

**Issue by dlangille** [Phorum/Core#967]
There is no urgency to this request.

Many years ago, I started hosting lists.phorum.org.  It has not been used since 2010.  It is time for it to retire.

Please remove the DNS entry pointing to 64.90.182.112 and I will ensure the reverse is cleared out.

If anyone wants the archives, they are at http://lists.phorum.org/pipermail/phorum-announce/ but that will not be accessible once the DNS changes mentioned above are completed.

**Comment by mysnip** [comment]
Done, thanks for hosting it for such a long time!

**Comment by oricgn** [comment]
What about http://www.phorum.org/list.php ? It should be deleted also, or?

**Comment by oricgn** [comment]
http://www.phorum.org/list.php now redirects to index.php, links to list.php removed.
