### ISSUE TITLE
Database error on Postgres

### ISSUE THREAD

**Issue by jimski777** [Phorum/Core#989]
After installing on Postgres 9.3 and trying to save the initial settings (admin.php) the following error occurs:

Phorum Database Error
Sorry, a Phorum database error occurred.
Please try again later!
Error:
ERROR: relation "forum__pm_messages" does not exist LINE 1: UPDATE forum__pm_messages ^ (42P01): UPDATE forum__pm_messages SET author = 'central' WHERE user_id = 1
Backtrace:
Function interact() called at
{path to Phorum}\include\db\PhorumDB.php:4313
----
Function user_display_name_updates() called at
{path to Phorum}\include\admin\update_display_names.php:84
----
Function require_once() called at
{path to Phorum}\admin.php:125

**Comment by mysnip** [comment]
There is no support for postgres in the core, therefore contact the author of the pgsql support.
